/**
 * build.mjs - compile dict/ru/*.json into lib/client.js.
 *
 * lib/client.js is COMMITTED so installing from GitHub never needs a build step.
 * Run this after editing any dictionary:
 *
 *   node scripts/build.mjs
 *
 * Output format: harness client-module loader bundle (window.__ModuleLoader__.load).
 * Raw ESM breaks the combo script parser and kills the whole app boot.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dictDir = join(root, 'dict', 'ru')
const outFile = join(root, 'lib', 'client.js')
const PKG = 'dsh-locale-ru'
const BT = String.fromCharCode(96)
const D = String.fromCharCode(36)

let files
try {
  files = readdirSync(dictDir).filter((f) => f.endsWith('.json')).sort()
} catch {
  console.error('build: dict/ru/ not found - nothing to build')
  process.exit(1)
}
if (files.length === 0) {
  console.error('build: dict/ru/ is empty - nothing to build')
  process.exit(1)
}

/** @type {Record<string, Record<string, string>>} */
const dictionaries = {}
for (const file of files) {
  const ns = file.replace(/\.json$/, '')
  const parsed = JSON.parse(readFileSync(join(dictDir, file), 'utf8'))
  // deterministic key order keeps the committed bundle diff-friendly
  dictionaries[ns] = Object.fromEntries(Object.entries(parsed).sort(([a], [b]) => a.localeCompare(b)))
}

const banner = [
  '// GENERATED by scripts/build.mjs - do not edit by hand.',
  '// Edit dict/ru/*.json and run node scripts/build.mjs instead.',
  '// Format: harness client-module loader bundle (window.__ModuleLoader__.load).',
  '',
].join('\n')

const lines = [
  'window.__ModuleLoader__.load({',
  '\tid: "' + PKG + '",',
  '\tfactory: (require) => {',
  '\t\tvar module = { exports: {} };',
  '\t\tvar exports = module.exports;',
  '\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });',
  '',
  '\t\tconst LANGUAGE = { id: \'ru\', label: \'Русский\', fallback: \'en\' };',
  '',
  '\t\tconst DICTIONARIES = ' + JSON.stringify(dictionaries, null, 2) + ';',
  '',
  '\t\tconst inject = [\'locale\'];',
  '',
  '\t\tfunction apply(ctx) {',
  '\t\t\tctx.effect(',
  '\t\t\t\t() => ctx.locale.addLanguage(LANGUAGE),',
  '\t\t\t\t\'' + PKG + ': language\',',
  '\t\t\t)',
  '\t\t\tfor (const [ns, dict] of Object.entries(DICTIONARIES)) {',
  '\t\t\t\tctx.effect(',
  '\t\t\t\t\t() => ctx.locale.register(ns, \'ru\', dict),',
  '\t\t\t\t\t' + BT + PKG + ': ' + D + '{ns} dictionary' + BT + ',',
  '\t\t\t\t)',
  '\t\t\t}',
  '\t\t}',
  '',
  '\t\texports.name = \'' + PKG + '\';',
  '\t\texports.apply = apply;',
  '\t\texports.inject = inject;',
  '\t\treturn module.exports;',
  '\t},',
  '});',
  '',
]

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, banner + lines.join('\n'))
const namespaces = Object.keys(dictionaries).length
const keys = Object.values(dictionaries).reduce((sum, d) => sum + Object.keys(d).length, 0)
console.log('build: wrote ' + outFile + ' (' + namespaces + ' namespaces, ' + keys + ' keys)')
